zooniverse/panoptes-javascript-client

README.md
Noticed this link was taking you to github.com/zooniverse/panotpes-javascript-client/blob/master/github.com/brian-c/json-api-client which didn't seem right.
=> Fix URL typo in the README

LICENSE.txt, README.md, package.json
IIRC we use Apache 2.0 as the standard Zoo licence, so this PR adds that in.
=> Set license to Apache 2

lib/auth.js, src/auth.js, test/auth.js
- Related to #8 
- Panoptes recently changed to using `user.login` over `user.display_name` as the canonical, unique form by which users are referenced. This brings the client up to date.
=> Use user.login instead of user.display_name

bower.json
The version number in `bower.json` is behind that in `package.json`. This brings it up to date; we'll probably need to delete the previous 0.1.2 tag and tag this commit instead.
=> Match bower.json version with package.json

lib/config.js
This PR (a whitelist+fail dangerous fix) is an alternative to PR #22 (a fallback+failsafe fix). Please close PR #22 if this PR is merged, or vice versa.
Symptoms:
* When using the Panoptes client in apps, the app will sometimes - depending on the process environment - throw an error, notably `Uncaught SugarClient.host is not defined`
* See: https://github.com/zooniverse/wildcam-gorongosa-education/pull/22#issuecomment-179395232
Analysis:
* We've detected that the `env` variable in lib/config.js doesn't always have one the valid values, i.e. 'production', 'staging' or 'cam'.
Actions:
* Recommendation: add a value **whitelist** so the `env` var cannot be invalid; **throw an error** otherwise.
@brian-c , this is based on our discussion in …
=> Alternate fix for `env` variable in lib/config.js

index.js, lib/oauth.js, package.json
I rewrote my previous implementation largely from scratch, and I think it's a lot better for it.
This version will eventually do all token handling itself, and request new tokens via an iFrame, so no page redirects are needed outside of the initial auth. That's currently blocked by zooniverse/Panoptes#1673
It'll also have a much simpler API - `init` to enable URL watching etc, then `checkCurrent`, `signIn` and `signOut`.
Currently a work in progress, please do not merge.
=> Another go at an OAuth module

index.js, lib/config.js, package.json
We are having trouble consuming panoptes-client npm package because the main in package.json was set to a file that no longer exists. This pull request fixes that, as well as adding strings to make "development" a meaningful environment name in addition to staging.
The npm package will need to be version-bumped after this change is accepted.
=> fix broken entry point in package.json, add development strings

lib/auth.js, lib/oauth.js
This could possibly fix #41.
It appears that tokens are expired momentarily (~20 seconds) before a refresh is issued.  Bumping the refresh request to a minute before expiry could fix this.
=> Increase TOKEN_EXPIRATION_ALLOWANCE to prevent token expiration

lib/stats-client.js, package.json, test/stats.js
Minor updates for more consistent style with the rest of the library. Mainly `workflowID`, not `workflow_id`.
Also stubbed in a dumb test just to see how it works.
=> Tweak stats client for consistency, stub out a test

lib/api-client.js, lib/auth.js
Depends on zooniverse/json-api-client#30.
Instead of using `setTimeout` to fetch a new bearer token before the current one expires, this gives the auth module a `checkBearerToken` method (which will refresh if needed) and calls if `beforeEveryRequest` on the API client.
We also talked about refreshing the token and remaking requests when we get a 401, which I thought would require a major rewrite, but now that I think about it again it might not be a big deal. Any strong preference for me to look into it more?
(The `handleError` method is just moved, add `&w=1` to the PR URL to ignore it.)
=> Auto refresh bearer token

lib/auth.js
Not sure what the rules are for hitting /oauth/token from www.zooniverse.org vs. panoptes.zooniverse.org. Should I switch this in the oauth module too?
=> Auth module does auth wth the normal host

lib/auth.js
Cache the promise for the token refresh request so that multiple aren't made at the same time.
(Changes are mostly whitespace.)
=> Only make one token refresh request

lib/api-client.js
Alternative to #62 
This keeps the old error message generator, for backward compatibility, but adds the HTTP status code and text to the returned error.
=> Add HTTP status to errors

lib/api-client.js, lib/config.js, lib/talk-client.js
Should enable the client to make use of HTTP caching in the Panoptes API, for SGL.
=> Add http_cache=true to all requests

lib/api-client.js, package.json
When using `typeof` on `null` it returns as an object. With the 500 error, the response body is null. Right now, that means that there will be a type error on line 20 since we're not checking for the existence of the response body. 
This also leads the question of how we should be handling 500 errors and if the client should be doing something differently. This PR will at least fix the type error.
=> Check for response.body for 500 errors

package.json
Updates json-api-client to accept query params on POST and PUT requests.
Required for zooniverse/pandora#46
=> json-api-client 3.3

lib/talk-client.js
Share the `beforeEveryRequest` method between the API client and the Talk client.
Fixes zooniverse/Panoptes-Front-End#4179
=> Check the bearer token before talk client requests

lib/oauth.js, package.json
Use window session storage to store the current bearer token across page reloads, in case 3rd party cookies are blocked.
I think this will fix #72, where sign-in does not work on sites like antislaverymanuscripts.org if 3rd party cookies are disabled.
It does not fix token refreshes, for long sessions, being blocked in that case.
=> Persist bearer token details across page reloads

lib/oauth.js
Array destructuring isn't supported in IE, so remove it.
=> Remove array destructuring from parseUrl()

lib/oauth.js, package.json
Towards #76 
Stores an `expires_at` timestamp with new tokens. Adds a `checkBearerToken` method that can be used by client apps to check the token, and refresh it if possible.
Tries, as far as possible, to copy the equivalent methods in the [Auth](/zooniverse/panoptes-javascript-client/tree/master/lib/auth.js) module.
```javascript
oauth.checkBearerToken()
.then(function (token) {
// I'm probably still logged in
})
.catch(function (error) {
// refreshing the token failed
}
```
=> Add checkBearerToken() to OAuth

lib/oauth.js, package.json
- Don't clear the saved token before a refresh. We might need to use it before we receive the new token.
- Return null from the refresh if we can't obtain a token.
- Call `checkBearerToken()` on initial load, if no token is present in the URL.
=> OAuth improvements

CHANGELOG.md, lib/oauth.js, package.json
Fixes a few bugs in 2.9.3: 
- The Promise returned from `oauth.init()` never resolves.
- Refreshing the token via an iframe did not return a valid token object. (Closes #84)
=> Various OAuth bug fixes

lib/oauth.js
Replaces `_checkPanoptesSession()` with `_getNewToken()`, which attempts to get a new token from Panoptes via an iframe (and should do only that.) Stored tokens are not returned, since we should only be calling this method when the stored token is about to expire.
Fixes a problem mentioned in https://github.com/zooniverse/shakespeares_world/issues/366#issuecomment-362587573 which is that the client would always return an expired token, if it was stored in session storage.
Also fixes a bug where `checkBearerToken` throws an error when getting a new token, because `this._deleteBearerToken` is undefined in the catch block here https://github.com/zooniverse/panoptes-javascript-client/blob/595e694c71dd877ddbae4a13e670fc466314258e/lib/oauth.js#L279-L284
=> Replace _checkPanoptesSession with _getNewToken

lib/oauth.js
Fixes #90 by persisting your auth token across browser tabs and sessions.
My naming was not great here. SESSION_STORAGE refers to your login session, not the browser session.
=> Use local storage for session tokens

lib/oauth.js
This makes the redirects built into the oauth client optional. The fixes put into place for ASM fixed [an old bug](https://github.com/zooniverse/panoptes-javascript-client/pull/75/files#r164709450) that the custom redirect behavior in Zooniverse Classrooms relied upon. We still want this custom redirect behavior for the classroom join page. This adds an options object to the `init` call where we can set this. When `true`, the `location.assign` call in the initialization will not be called. 
There aren't any tests written for the oauth client, so we'll have to do some manual testing 🤷‍♀️ I'll open a parallel PR on edu-api-front-end.
=> Optional redirect

lib/api-client.js
Check for response.body before checking for response.body.error or response.body.errors.
Don't sniff the response for <DOCTYPE.
Report 'unknown error' with status and status text if the response body is empty.
Fixes a bug where the client crashes on 500 errors, because `response.body` is null.
Closes #99.
=> Return an error for empty response body

lib/oauth.js
The `doorkeeper` dependency in Panoptes has been bumped up to 4.4.1, which changes the bearer token to the **Bearer** token (capital B). This change means that users of Custom Front End projects won't be able to sign in, as the panoptes-client won't recognise the (lower-case) bearer token being passed back to the app.
This PR fixes the issue by changing the check to accept either `token_type=Bearer` or `token_type=bearer`.
Ready for review, and more thorough testing needed; I'm not sure if I'm missing anything beyond the sign-in problems on localhost that I'm experiencing.
=> Doorkeeper 4.4.1 compatibility

lib/stats-client.js, package.json, test/index.js, test/stats.js
- updates statsClient to accept user_id, added in https://github.com/zooniverse/zoo-event-stats/pull/83
- refactors queries to data object as per [makeHTTPRequest](https://github.com/zooniverse/json-api-client/blob/master/src/make-http-request.coffee#L30)
- updates related test, though test could be improved, this client will be phased out, so didn't dive into
This functionality will allow the new [Notes from Nature Field Book](https://github.com/zooniverse/notes-from-nature-field-book) to provide user stats in a way greatly desired by the research team and volunteers.
=> Update stats-client for user_id query

lib/config.js
This PR adds `test` env variables for several items. This is being added for apps using create-react-app, as the bootstrapper does not allow setting the `NODE_ENV` manually. Thus, running commands like `yarn test` would cause the PJC to throw an error since the `test` env isn't recognized.
=> Add Variables for a Test Environment

lib/auth.js, lib/config.js, lib/csrf-token.js, lib/oauth.js, package-lock.json, package.json, test/auth.js
Use the underlying credentialed / non-credentialed http requests in https://github.com/zooniverse/json-api-client/pull/52 to avoid CORS issues for open resources on the API.
The underlying issue is that an API change to cors implementation in https://github.com/zooniverse/Panoptes/pull/3199 ensures that all public (wildcard) origins disallows credentialed requests, i.e. our API allows `{ origins: '*', resource: 'api/*'}` so these resources can't be accessed with credentialed requests. As it stands our `json-api-client` always attaches uses `withCredentials` which is a risk of leaking private data.
=> [WIP] use withCredentials XMLHTTPRequest appropriately

lib/config.js
This PR changes PJC's oAuth host:
- The default oAuth host is now `www.zooniverse.org` instead of `panoptes.zooniverse.org`, to reflect current changes to the backend. That's right! oAuth users now sign in via our "main domain" instead of the `panoptes.` sub-domain.
- The oAuth host can now also be changed either by setting `?oauth-host=...` in the browser, or setting `OAUTH_HOST` in the env build variables. This brings the oAuth host config setting in line with other editable items in the PJC's config.
To Custom Front End developers:
- This change will allow **single sign on** across all `*.zooniverse.org` domains (if you use the oauth.js code)
- If you implement these changes, you should see **no changes** to sign-in functionality. The only difference should be that when users login, …
=> Change default oAuth Host and allow config

lib/config.js
This PR adds a check in the config file for an environment variable set via Create React App. This is necessary for deploying ALICE to staging. 
ALICE is built using Create React App, which strictly sets `NODE_ENV` to `production` when running `react-scripts build`. Although you can [set custom variables](https://create-react-app.dev/docs/deployment/#customizing-environment-variables-for-arbitrary-build-environments) (like `REACT_APP_ENV`), you are not allowed to change the node environment (see Special Thanks on [link](https://dev.to/jam3/managing-env-variables-for-provisional-builds-h37)), as it is strictly set.
You can eject Create React App to set the `NODE_ENV`, but this is a pretty drastic thing to do, and you lose all the convenience of having CRA handle your dependencies.
=> Check for Custom ENV Variable from CRA

lib/auth.js, lib/oauth.js
Hide underscored methods and properties from the exported `auth` and `oauth` clients.
~~Change the signature of `auth.checkBearerToken()` so that it resolves true/false rather than resolving with the bearer token.~~
`npm install zooniverse/panoptes-javascript-client#private-data` to try this out.
=> Auth clients: Hide private data from exports

CHANGELOG.md, lib/sugar.js
`auth._bearerToken` is undefined as of 3.3.0, so pass the token to Sugar from `auth.checkBearerToken()`.
Check the current token before each Sugar API request.
=> Update Sugar client token handling

test/index.js
Closes #138 
When #124 was merged we forgot to remove the line that tries to test the `./auth` test file. This removes that line and allows `npm run test` to run again
=> Remove auth test module

lib/auth.js
linked to reports of folks submitting classifications but not having them attributed to their account (i.e. not linked to the user), https://www.zooniverse.org/projects/douglas-clark/the-arctic-bears-project/talk/2102/1955932?comment=3221410
In theory these events should be rare but there are known service issues with the K8s ingress where it temporarily loses the ability to route traffic to the service pods and thus this could be exacerbating this issue.
I theorized that this event could happen if the request to refresh a token fails or times out (due to network or API service issues) and in the interim period when the current token expires there is no request to the API to refresh it again. 
Thus this PR introduces a change to refresh the token at a much earlier point (5 mins vs 1 min) …
=> increase token expiration allowance to 300s (5mins)

lib/sugar.js
Missed in #135: `Promise.all` should take an array as an argument. I've also added better error-logging to debug Sugar client errors.
=> Sugar client: fix Panoptes authentication

package-lock.json, package.json
This is a minor update to the sugar client that did two things: decaffeinate the coffeescript of the client and remove the build tools of browserify, watchify, uglify. The browserify build tools weren't even being used. The coffeescript version it used was very old and although there had been updates since, the coffeescript project is moving very slow these days. Decaffeinating the client seems the best way forward.
This should be tested using npm link with PFE to confirm that it doesn't break the notification system.
=> Update sugar-client to 1.1.0

CHANGELOG.md, lib/auth.js
Return the refreshed token, or an empty string, from `auth._refreshBearerToken()`. This should fix token-handling for code that expects `auth.checkBearerToken()` to return a valid token.
=> Return a token from auth._refreshBearerToken

CHANGELOG.md, package-lock.json, package.json
release v3.3.5 which includes an update to the sugar client (v2.0.0)
I'll publish this to npm once this is merged
=> bump version to v3.3.5

CHANGELOG.md, package-lock.json, package.json
Includes a major version bump for `local-storage` and a minor version bump for `json-api-client`, which upgrades `superagent` to v7.
=> Version 3.4.0

CHANGELOG.md, package-lock.json, package.json
Upgrade to JSON-API Client 6.0, which uses superagent 8. Drop support for Internet Explorer and Node 12. Upgrade `package-lock.json` to version 2.
I've tagged this as `v4.0.0` since it's a major change (particularly dropping support for older XHR requests.)
=> Upgrade to superagent 8. Drop Node 12.

lib/config.js
these aren't useful in deployed systems, instead rely on `*FromShell` config overrides for development
=> remove *FromBrowser config directives

CHANGELOG.md, package-lock.json, package.json
Includes a bump of superagent from 8.0.1 to 8.0.2, via `json-api-client@6.0.2`
=> Version 4.1.1

lib/api-client.js
Reject the returned promise after catching an API error, rather than re-throwing the error.
This might make the PFE error logs less noisy, since we don't really want to error for 404 responses etc.
To install this in `npm` projects like PFE, point the `panoptes-client` package to this branch in `package.json`.
```json
"panoptes-client": "zooniverse/panoptes-javascript-client#reject-on-error",
```
then `npm ci` (or `npm ci --legacy-peer-deps` for older projects.)
=> Reject the returned promise on error

CHANGELOG.md, lib/api-client.js
Consumers of this client expect promises to reject with an [Error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error), not the API response body, so convert the response to an Error object before rejecting the returned promise.
Follow-up to #164. See https://github.com/zooniverse/Panoptes-Front-End/issues/6234 and https://github.com/zooniverse/Panoptes-Front-End/issues/6232.
=> Convert error responses to Error objects

CHANGELOG.md, package-lock.json, package.json
Converts Panoptes API response bodies to errors, for downstream clients that expect an `Error` object from rejected promises.
Some apps catch errors like this:
```js
apiClient.get(something)
.catch(error => error.toString())
```
`error.toString()` returns the error message for instances of [`Error`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error). Otherwise, it returns `[object Object]`.
```
=> Version 4.2.2

CHANGELOG.md, lib/auth.js
Make sure that the request promise is rejected with an error when login fails. Otherwise, it resolves with an undefined user.
This is based off #176, so merge that first.
- Fixes #177.
- See also https://github.com/zooniverse/Panoptes-Front-End/issues/6236.
=> lib/auth: Return login errors

lib/SugarClient/client.js, lib/SugarClient/primus.js, lib/sugar.js, package-lock.json, package.json
- add the Sugar and Primus 8 client libraries to `lib/SugarClient`.
- update `lib/sugar.js` to use the local libraries.
- remove `sugar-client`.
=> Upgrade Sugar to Primus 8

lib/json-api-client/resource.js
Update the `ResourcePromise` interface to match `Resource`, so that we can do the same things with resource promises that we do with resources.
Eg.
- `client.type().get().addLink()`
- `resource.save().addLink()`
=> Add Resource methods to ResourcePromise

lib/auth.js, lib/oauth.js
Add the enumerable values of `config.jsonHeaders` to `deleteHeaders`, rather than [creating a new, empty object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create#syntax) from its prototype.
Closes #197.
=> Add default JSON headers to sign-out requests

lib/auth.js
Swap `apiClient.put` for `makeCredentialHTTPRequest` in `auth.changePassword` and `auth.resetPassword`.
This should allow those client methods to work even when the client and the API are not on the same origin eg. when using the staging API.
Closes #199.
I've set up https://github.com/zooniverse/Panoptes-Front-End/pull/6436 to test this branch, so you can try out the changes on https://pr-6436.pfe-preview.zooniverse.org.
=> Use credentialed requests for password updates

lib/auth.js, lib/oauth.js
Related: https://github.com/zooniverse/panoptes/pull/4134
https://github.com/zooniverse/how-to-zooniverse/issues/319
Edit: Add missing Bearer Authorization Header on Signout
=> add bearer token on signout 

lib/auth.js, lib/oauth.js
Refactor `auth.signOut` and `oauth.signOut` to remove nested promises and `.bind(this)` on inner functions. Use `async/await` instead, for better readability.
Use `auth.checkBearerToken()` to get the bearer token for the DELETE request.
=> Refactor signOut with async/await

lib/sugar.js
Refresh Sugar client auth tokens so that we don't get expired token errors from long-running sessions.
=> Refresh Sugar client tokens

lib/SugarClient/client.js, lib/api-client.js
Add `client.refreshToken()` to the Sugar client. Call it whenever `client.primusUrl()` generates a URL for the Primus service.
=> Sugar client: add token refresh

lib/SugarClient/client.js, lib/api-client.js, lib/auth.js, lib/sugar.js
- Emit a 'refresh' event from `auth` for each new token.
- Refactor `sugarClient.refreshToken()` to update the Sugar client token on `refresh` events.
- Reconnect to Primus when the token changes, so that the Primus URL changes.
=> Improved Sugar client token refresh flow

lib/auth.js
Replace nested promises with `async/await` throughout the `auth` module. This breaks backwards compatibility with IE.
=> Refactor auth with async/await

lib/auth.js
- Replace `this.update` with `this.emit` throughout the `auth` module.
- ~~Wait for API requests to resolve with a response before emitting 'change' events on sign in and on registration.~~ Waiting for promises to resolve breaks `checkCurrent()` when no one is logged in.
=> Auth module: explicitly emit 'change' events

lib/auth.js
Wait for API calls to resolve before emitting `change` events on sign out. Otherwise, `change` is fired while we still have a signed-in session in Panoptes.
=> Bugfix: defer 'change' events on sign out

lib/SugarClient/primus.js
This permanently removes the two browser hacks that were temporarily removed from Primus in #223.
=> SugarClient: Bump Primus to 8.0.9

lib/config.js, lib/eras-client.js
Adding simple ERAS client for Project Stats Callouts. 
I mainly focused on callouts that will be used for project stats (as opposed to using statsClient on PFE). 
One thing I did not add for eras client are the future callouts that will be used. Eg. Getting classification counts by user_group (`/classifications/user_groups/:id` or getting classification count by user `/classifications/users/:id`). I figured that would be done in a future iteration when we are ready to cross that bridge. (I don't mind adding it on now if we want to have it available in PJC now).
=> add eras-client for projects stats callouts

README.md
Similar to https://github.com/zooniverse/markdownz/pull/250 , update readme publishing steps for Zooniverse members without push access to `main`.
=> Update readme publishing steps
