CHANGELOG.md, README.md
As per our emails, I've added a changelog and info about those conventions to the README
=> Add a Changelog

lib/config.js
this was too specific and consistent with sugar hosts, etc
=> remove cam env form the client repo

examples/oauth.js, lib/config.js, lib/oauth.js, package.json
=> Add panoptes.zooniverse.org for OAuth

lib/config.js
This adds the configuration for the stats server in preparation for the new PFE project stats page.
=> add stats sever

lib/stats-client.js
Set project and workflow via statsClient.update().
Get stats with statsClient.statCount(period, type).
=> Add a simple statsClient object

lib/oauth.js
=> Fix regex to correctly match new token rules

CHANGELOG.md
Tried a generating a changelog using the [github changelog](https://github.com/skywinder/github-changelog-generator) gem.
=> Massive changelog update

package-lock.json, package.json
Add package-lock.
Upgrade json-api-client.
=> Audit packages

lib/config.js
allow dev and staging deploys to fetch stats from the live stats staging API.
=> add staging / dev event stats server

package-lock.json, package.json
=> json-api-client 4.0.1

package-lock.json, package.json
Update to 4.0.2 which applies some security patches.
=> update JSON-API client

package-lock.json, package.json
This updates outdated packages, including a security fix for lodash.
=> v2.12.3: Security patch

package-lock.json, package.json
Updating the json-api-client dependency to 5.0.0 and bumping this to 3.0.0.
=> Major version 3

CHANGELOG.md, package-lock.json, package.json
This PR updates PJC's version and updates the changelog. Note: I'm also adding changelog deets for 3.0.0 to keep everything updated.
=> Minor version 3.1.0

CHANGELOG.md, package-lock.json, package.json
Security patch to update the JSON-API client.
=> version 3.2.1

CHANGELOG.md, package-lock.json, package.json
Minor version bump with changelog entry.
=> Minor bump

.github/workflows/codeql-analysis.yml
=> setup GH security scanning

CHANGELOG.md, package-lock.json, package.json
Includes updated sugar client.
=> Bump version to 3.3.3

package-lock.json, package.json
linked to https://github.com/zooniverse/Sugar-Client/pull/18
=> bump sugar client version to 2.0.0

package-lock.json, package.json
No changes here, just a patch for `minimist` in the dev dependencies.
=> Version 3.3.6

.github/workflows/ci-tests.yml
add github action to run the CI test suite...it's minimal but probably worth adding to the PRs to make sure the app builds and can run what test it has...
=> add CI system to run what tests there are

CHANGELOG.md, package-lock.json, package.json
Changelog and version tag for 4.2.0.
=> Version 4.2.0

CHANGELOG.md, package-lock.json, package.json
- Bump minimatch to 3.1.2.
- Bump json-api-client to 6.0.3.
=> [Security] Version 4.2.1

CHANGELOG.md, package-lock.json, package.json
A small fix for error handling in `auth.signIn` when either the login or password are incorrect.
=> Version 4.2.3

documentation.md
A first pass at documenting the auth module. Documents signing in and signing out, changing a password, establishing a session and refreshing an access token.
=> Document the Auth module

lib/auth.js
Wait for API promises to resolve before emitting 'change' events.
=> Auth: defer change events

lib/auth.js
Fix a missing payload for the token refresh request.
=> Bugfix: Auth token refresh flow

lib/SugarClient/primus.js
- download the latest Primus client from https://notifications.zooniverse.org/primus.js
- remove workarounds for bugs in Firefox 22 and Safari 5.
=> SugarClient: Update Primus
